// Backup cards, used when the AI is off or can't be reached.
window.TOD_BANK = {
  truth: [
    "What's the most embarrassing thing you've done while drunk?",
    "Who in this room would you call first if you got arrested?",
    "What's the worst date you've ever been on?",
    "What's a secret you've never told your parents?",
    "Who was your first crush, and do they know?",
    "What's the most childish thing you still do?",
    "Have you ever stalked an ex on social media? How deep did you go?",
    "What's the biggest lie you've told to get out of plans?",
    "Which person here would survive the longest in a zombie apocalypse, and who would go first?",
    "What's the weirdest thing you've searched on Google?",
    "What's your most irrational fear?",
    "Have you ever pretended to like a gift? What was it?",
    "What's the last thing you cried about?",
    "Which song do you secretly love but would never admit to?",
    "What's the pettiest reason you stopped talking to someone?",
    "What's the worst thing you've done at work or school and never got caught for?",
    "If you could swap lives with someone here for a week, who would it be?",
    "What's the most money you've wasted on something stupid?",
    "What's a red flag you ignored in a past relationship?",
    "Have you ever ghosted someone? Why?",
    "What's the most awkward thing that's happened to you on a night out?",
    "What's your guilty pleasure TV show?",
    "What's one thing you'd change about yourself if you could?",
    "Who here do you think has the best style?",
    "What's the craziest thing you've done for love?",
    "What's the meanest thing you've ever said to someone?",
    "Have you ever lied in this game?",
    "What's something you're proud of that nobody here knows?",
    "What's the most cringe photo on your phone right now?",
    "What's the strangest dream you've had about someone you know?",
    "Who was the last person you texted, and what did you say?",
    "What's the worst haircut you've ever had?",
    "What's a habit of yours that you know annoys people?",
    "What was your most embarrassing moment in school?",
    "Have you ever had a crush on a friend's partner?",
    "What's the longest you've gone without showering?",
    "What's the most rebellious thing you did as a teenager?",
    "Which celebrity would you date if you could?",
    "What's your biggest regret from the last year?",
    "What's the worst text you've sent to the wrong person?",
    "What do you think people get wrong about you?",
    "Have you ever eaten something off the floor in public?",
    "What's the most spontaneous thing you've ever done?",
    "If you had to delete one app forever, which would hurt the most?",
    "What's the most embarrassing thing in your search history?",
    "What's the weirdest thing you find attractive?",
    "What's something you've never admitted to your best friend?",
    "When was the last time you lied, and what about?",
    "Which person here would you trust with your phone unlocked?",
    "What's the worst thing you've ever cooked?",
    "Have you ever been kicked out of somewhere? Where?",
    "What's the most attention-seeking thing you've posted online?",
    "What's one thing you'd never do, no matter how much you were paid?",
    "What's the dumbest way you've ever hurt yourself?",
    "Who here would you want as your wingman or wingwoman?",
    "What's your most used emoji, and what does it say about you?",
    "Have you ever had a fake social media account?",
    "What's your worst habit when you're stressed?",
    "What's a compliment you've never forgotten?",
    "What's something you pretend to understand but actually don't?",
    "What's the most awkward thing you've said to a crush?",
    "If your life was a movie, what would the title be?",
    "What's the last thing that made you really jealous?",
    "What's the worst advice you've ever followed?",
    "Which ex would you most like to bump into looking your best?",
    "What's the most out-of-character thing you've ever done?",
    "What's something you've done that you hope your future kids never find out?",
    "What's the oddest thing you've done to impress someone?",
    "Who in this room do you know the least, and what's your first impression of them?",
    "What's one rule you always break?"
  ],
  dare: [
    "Let the person on your left post a story from your phone.",
    "Do your best impression of someone in this room until someone guesses who.",
    "Send a voice message singing happy birthday to the third person in your recent chats.",
    "Talk in a dramatic movie trailer voice until your next turn.",
    "Let the group choose a new profile picture for you for 24 hours.",
    "Do 15 squats while saying the alphabet backwards.",
    "Show the group the last 5 photos in your camera roll.",
    "Call a friend and tell them you've decided to become a professional mime.",
    "Dance with no music for 30 seconds.",
    "Let someone draw a small tattoo on your arm with a pen.",
    "Speak in rhymes until your next turn.",
    "Give a 30-second TED talk about your favourite snack.",
    "Text your crush or your last ex a single emoji of the group's choice.",
    "Swap one item of clothing with the person to your right.",
    "Let the group read your last three Google searches out loud.",
    "Do a runway walk across the room like it's fashion week.",
    "Eat a spoonful of a condiment of the group's choice.",
    "Compliment every person in the room in under one minute.",
    "Imitate a famous singer until someone guesses who it is.",
    "Hold a plank until the person after you finishes their turn.",
    "Let the group write a tweet or story caption that you have to post.",
    "Serenade the person opposite you with a love song.",
    "Do your best evil villain laugh.",
    "Narrate everything the next player does like a nature documentary.",
    "Speak with an accent of the group's choice for the next three rounds.",
    "Let the person to your right style your hair however they want.",
    "Do your most dramatic fake cry.",
    "Write a short poem about the host and read it out loud.",
    "Do a 20-second freestyle rap about the person on your left.",
    "Let someone go through your Spotify and judge your top song.",
    "Act out your morning routine in slow motion.",
    "Pretend to be a waiter and take everyone's drink orders.",
    "Do a cartwheel, or your best attempt at one.",
    "Text your mum or dad 'I have something important to tell you' and wait 2 minutes before explaining.",
    "Keep an ice cube in your hand until it melts or your next turn.",
    "Let the group choose a word you must say in every sentence until your next turn.",
    "Do your best robot dance for 30 seconds.",
    "Show the most embarrassing photo in your gallery.",
    "Recreate a famous movie scene with someone of your choice.",
    "Let the person to your left send a message to any contact they pick, approved by you.",
    "Pretend you're a cat until your next turn, and only meow when you speak.",
    "Try to lick your elbow.",
    "Give someone in the room a two-minute shoulder massage.",
    "Say something nice and specific about the last person who dared you.",
    "Tell a joke. If nobody laughs, take a sip.",
    "Balance a spoon on your nose for 10 seconds.",
    "Do your best impression of the host.",
    "Read the last message you sent out loud, with dramatic emotion.",
    "Let the group pick a song and lip-sync to it.",
    "Go outside and shout 'I love this party' as loud as you can.",
    "Wear your clothes inside out until the end of the round.",
    "Do a magic trick. Any magic trick.",
    "Act like a sports commentator describing the room for 30 seconds.",
    "Hug the person you've known the shortest time.",
    "Let someone change your phone wallpaper for the rest of the night.",
    "Describe your love life using only movie titles.",
    "Make up a 20-second advert for the drink in your hand.",
    "Say the alphabet while everyone tries to make you laugh.",
    "Do a slow-motion run across the room with sound effects.",
    "Give your best acceptance speech for an award you'll never win.",
    "Let the group choose an emoji you must use as your only reply in chats tonight.",
    "Attempt to juggle three items the group chooses.",
    "Talk without closing your mouth until your next turn.",
    "Pick someone to switch seats with and imitate them for one round.",
    "Show everyone your screen time report.",
    "Do a dramatic reading of the ingredients on any package nearby.",
    "Let the group give you a new nickname you must answer to tonight.",
    "Speak only in questions until your next turn.",
    "Do your best TikTok dance.",
    "Post 'I have an announcement' on your story with no explanation for 10 minutes."
  ]
};
